# Machine Learning Lab

## Lab 01 – Introduction to Python for Data Analysis

Name: Shrija Suman

Aim:
Introduction to Python for Data Analysis focusing on NumPy and Pandas.

In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Datatype:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Datatype: int64


In [4]:
zeros_matrix = np.zeros((3,4))
ones_matrix = np.ones((2,5))

print("Zeros Matrix:")
print(zeros_matrix)

print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:")
print(ones_matrix)

print("Shape:", ones_matrix.shape)

Zeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [5]:
arr = np.arange(1,13)

print("Original Array")
print(arr)

reshaped = arr.reshape(3,4)

print("\nReshaped Array")
print(reshaped)

print("Original Shape:", arr.shape)
print("Reshaped Shape:", reshaped.shape)

Original Array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Shape: (12,)
Reshaped Shape: (3, 4)


In [6]:
arr = np.random.randint(1,100,10)

print("Array:", arr)

print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())

Array: [24  7 43 50 35 68 18 37 60 61]
Minimum: 7
Maximum: 68
Mean: 40.3
Sum: 403


In [7]:
data = {
    "Name":["Aman","Riya","Karan","Sneha"],
    "Marks":[85,90,78,92]
}

df = pd.DataFrame(data)

print(df)

print("\nData Types:")
print(df.dtypes)

    Name  Marks
0   Aman     85
1   Riya     90
2  Karan     78
3  Sneha     92

Data Types:
Name       str
Marks    int64
dtype: object


In [10]:
import pandas as pd

data = {
    "Name": ["Aman","Riya","Karan","Sneha","Arjun"],
    "Math": [85,90,78,92,88],
    "Science": [80,85,75,95,89]
}

df = pd.DataFrame(data)

df.to_csv("students.csv", index=False)

In [11]:
df = pd.read_csv("students.csv")

print("First 5 records")
print(df.head())

print("\nLast 5 records")
print(df.tail())

First 5 records
    Name  Math  Science
0   Aman    85       80
1   Riya    90       85
2  Karan    78       75
3  Sneha    92       95
4  Arjun    88       89

Last 5 records
    Name  Math  Science
0   Aman    85       80
1   Riya    90       85
2  Karan    78       75
3  Sneha    92       95
4  Arjun    88       89


In [12]:
df = pd.read_csv("students.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str  
 1   Math     5 non-null      int64
 2   Science  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes


In [13]:
df = pd.read_csv("students.csv")

print(df.describe())

            Math    Science
count   5.000000   5.000000
mean   86.600000  84.800000
std     5.458938   7.758866
min    78.000000  75.000000
25%    85.000000  80.000000
50%    88.000000  85.000000
75%    90.000000  89.000000
max    92.000000  95.000000
